getpy*: resived FIX=1 option, default PIP=1 version, VENV=1

diff --git a/bin/getpy2 b/bin/getpy2
--- a/bin/getpy2
+++ b/bin/getpy2
@@ -16,8 +16,10 @@ if [[ $1 == --help || $1 == help || $HELP == 1 ]]; then
 		CHECK=1      Only check and report, do not install
 		PIP=1        Also install latest pip
 		PIP=version  Also install pip of the specified version
+		VENV=1       Install virtualenv
+		VENV=dir     Install virtualenv, create one in `dir`
 		FORCE=1      Install even if present
-		FIX=1        Create a /usr/local/bin/python symlink
+		FIX=1        Create /usr/local/bin/python2 symlink (default on macOS)
 		VERBOSE=1    Print commands
 		HELP=1       Print help
 
@@ -28,14 +30,29 @@ fi
 [[ $VERBOSE == 1 ]] && { set -x; PS4='$LINENO: '; }
 [[ -z $PIP ]] && PIP=0
 
+# pip 20.x is broken is the sense that it will not respect virtualenv's system-site-packages
+# thus requiring packages to be built from source in order to be installed.
+# Until this is fixed we stick to pip 19.3.1.
+[[ $PIP == 1 ]] && PIP=19.3.1
+
+# the end state should be:
+# in a python2 venv: `python` command (don't fix)
+# in a non-python2 venv or outside venv:
+#   mandatory: `python2` command (fix)
+#   optional: `python2.7` command (don't fix)
+#   optional: `python` command (don't fix)
+
 fix_variants() {
-	if [[ ! -z $PYTHON2 ]]; then
-		[[ -z $PYTHON && "$PYTHON_VER" == "2"  ]] && ln -s $PYTHON2 /usr/local/bin/python
+	if [[ ! -z $VIRTUAL_ENV ]]; then
+		[[ ! -z $PYTHON && "$PYTHON_VER" == "2"  ]] && return
 	fi
 
-	if [[ ! -z $PYTHON27 ]]; then
-		[[ -z $PYTHON2 ]] && ln -s $PYTHON27 /usr/local/bin/python2
-		[[ -z $PYTHON && "$PYTHON_VER" == "2" ]]  && ln -s $PYTHON27 /usr/local/bin/python
+	if [[ -z $PYTHON2 ]]; then
+		if [[ ! -z $PYTHON27 ]]; then
+			ln -sf $PYTHON27 /usr/local/bin/python2
+		elif [[ ! -z $PYTHON && "$PYTHON_VER" == "2"  ]]; then
+			ln -sf $PYTHON /usr/local/bin/python2
+		fi
 	fi
 }
 
@@ -59,6 +76,17 @@ check_variants() {
 }
 
 install_python() {
+	if [[ $(uname) == Darwin ]]; then
+		if [[ -z $(command -v brew) ]]; then
+			>&2 echo "Unable to install Python without brew. Aborting."
+			>&2 echo "Please install brew and retry."
+			exit 1
+		fi
+
+		# try to fix /usr/local/bin/python on macOS unless stated otherwize
+		[[ $FIX != 0 ]] && export FIX=1
+	fi
+
 	if [[ ! -z $(command -v apt-get) ]]; then
 		runn apt-get -qq update
 		runn apt-get -qq install -y python
@@ -103,7 +131,7 @@ install_pip() {
 	fi
 
 	runn wget -q -O /tmp/get-pip.py https://bootstrap.pypa.io/get-pip.py
-	runn $MYPY /tmp/get-pip.py "$pipspec"
+	runn $MYPY /tmp/get-pip.py $pipspec
 	rm -f /tmp/get-pip.py
 }
 
@@ -121,5 +149,10 @@ if [[ -z $(command -v $MYPY) ]]; then
 fi
 
 [[ $PIP != 0 ]] && install_pip
+
+if [[ ! -z $VENV ]]; then
+	$MYPY -m pip install virtualenv
+	[[ $VENV != 1 ]] && $MYPY -m virtualenv $VENV
+fi
 
 exit 0
